const SALE_ITEMS = [
  {
    id: 1,
    title: "West Elm Style Sofa",
    category: "Furniture",
    price: 250,
    originalPrice: 899,
    condition: "Good",
    status: "Available",
    image: "assets/images/sofa.svg",
    description: "Comfortable 3-seat sofa. Minor normal wear. Great for apartment or family room.",
    pickup: "Cupertino / Bay Area",
    reference: ""
  },
  {
    id: 2,
    title: "Dining Table with 4 Chairs",
    category: "Furniture",
    price: 180,
    originalPrice: 650,
    condition: "Good",
    status: "Available",
    image: "assets/images/table.svg",
    description: "Solid dining set. Seats 4 comfortably. Easy pickup from ground floor.",
    pickup: "Cupertino / Bay Area",
    reference: ""
  },
  {
    id: 3,
    title: "Keurig Coffee Maker",
    category: "Kitchen",
    price: 35,
    originalPrice: 120,
    condition: "Used",
    status: "Sold",
    image: "assets/images/coffee.svg",
    description: "Works well. Clean and ready to use.",
    pickup: "Cupertino / Bay Area",
    reference: ""
  },
  {
    id: 4,
    title: "Kids Board Games Bundle",
    category: "Kids & Toys",
    price: 25,
    originalPrice: 100,
    condition: "Good",
    status: "Available",
    image: "assets/images/games.svg",
    description: "Bundle of family board games. Good for elementary school kids.",
    pickup: "Cupertino / Bay Area",
    reference: ""
  },
  {
    id: 5,
    title: "Floor Lamp",
    category: "Home",
    price: 30,
    originalPrice: 95,
    condition: "Like New",
    status: "Available",
    image: "assets/images/lamp.svg",
    description: "Modern floor lamp. Warm light, simple design.",
    pickup: "Cupertino / Bay Area",
    reference: ""
  },
  {
    id: 6,
    title: "Office Chair",
    category: "Office",
    price: 75,
    originalPrice: 220,
    condition: "Good",
    status: "Available",
    image: "assets/images/chair.svg",
    description: "Comfortable office chair for work-from-home setup.",
    pickup: "Cupertino / Bay Area",
    reference: ""
  },
  {
    id: 7,
    title: "Air Fryer",
    category: "Kitchen",
    price: 45,
    originalPrice: 140,
    condition: "Good",
    status: "Available",
    image: "assets/images/airfryer.svg",
    description: "Compact air fryer, good condition. Perfect for quick cooking.",
    pickup: "Cupertino / Bay Area",
    reference: ""
  },
  {
    id: 8,
    title: "TV Stand",
    category: "Furniture",
    price: 90,
    originalPrice: 300,
    condition: "Good",
    status: "Available",
    image: "assets/images/tvstand.svg",
    description: "Clean TV console with storage shelves.",
    pickup: "Cupertino / Bay Area",
    reference: ""
  }
];
