// ============================================================
//  items.js — Generated from Google Sheet
//  https://docs.google.com/spreadsheets/d/1z85ue0Coc1Ev3xbVaTUksiJAoBe7R9WZ6UGFzOmjZW0
//  Last updated: July 1, 2026
//  DO NOT EDIT MANUALLY — update the sheet and re-generate
// ============================================================

const SALE_ITEMS = [
  {
    id: 1,
    title: "Dreo Tower Fan 36-Inch Oscillating Fan",
    category: "Electronics",
    price: "$35–45",
    originalPrice: "$79.99",
    condition: "Used – Good",
    status: "Available",
    image: "assets/images/1Ku9qRCodCtgQ0jJsu3d3ADgkbQjTLzgH.jpg",
    description: "Dreo brand bladeless-style tower fan with touch controls, remote receiver, and oscillation feature, suitable for all ages.",
    reference: "https://www.amazon.com/s?k=Dreo+Tower+Fan+36+Inch",
  },
  {
    id: 2,
    title: "Roller Derby Quick Fit Adjustable Quad Roller Skates – Pink Floral",
    category: "Other",
    price: "$18–25",
    originalPrice: "$49.99",
    condition: "Used – Good",
    status: "Available",
    image: "assets/images/1UayzGJPtO6HHEURKh1KtDFuiH3e2W40M.jpg",
    description: "Roller Derby brand kids' adjustable quad skates with Quick Fit sizing system, pink floral design, suitable for ages 5–10.",
    reference: "https://www.macys.com/shop/product?ID=roller+derby+quad+skates",
  },
  {
    id: 3,
    title: "Mid-Century Modern Green Chenille 3-Seat Sofa",
    category: "Furniture",
    price: "$250",
    originalPrice: "$600",
    condition: "Used – Good",
    status: "Available",
    image: "assets/images/1VVyW9qBytxDNrXJulnjIscs5p1dUuzCg.jpg",
    description: "Sage green chenille upholstery with walnut-finish tapered legs, three-cushion design, good condition with decorative white throw pillows included.",
    reference: "https://www.livingspaces.com/pdp-marques-heritage-green-84-inch-sofa-316042",
  },
  {
    id: 4,
    title: "Oxelo Fit5 Adjustable Inline Skates (Size 35–38)",
    category: "Other",
    price: "$20–28",
    originalPrice: "$59.99",
    condition: "Used – Moderate Wear",
    status: "Available",
    image: "assets/images/1fhnVllgbzuVX9qy9livF4ki-yeWi5G3q.jpg",
    description: "Decathlon Oxelo brand kids adjustable inline skates with orange wheels, size range 35–38 (approx US 3–5), showing moderate wear.",
    reference: "",
  },
  {
    id: 5,
    title: "Airwalk ABEC-5 Adjustable Inline Skates – Purple",
    category: "Other",
    price: "$18–25",
    originalPrice: "$49.99",
    condition: "Used – Good",
    status: "Available",
    image: "assets/images/1KGjltb29J9rFJ0sPAdufrKF9wJLCTpED.jpg",
    description: "Airwalk brand adjustable inline skates with ABEC-5 bearings, purple/black colorway, youth sizing with lace/velcro/buckle closure system.",
    reference: "https://www.walmart.com/search?q=Airwalk+inline+skates",
  },
  {
    id: 6,
    title: "Spalding Portable Basketball Hoop with Acrylic Backboard",
    category: "Other",
    price: "$150–220",
    originalPrice: "$299–499",
    condition: "Used – Good",
    status: "Available",
    image: "assets/images/1GR7sFGrVyPiKSa05zkH1nDhX6au8uiag.jpg",
    description: "Spalding brand adjustable-height portable hoop with clear acrylic backboard, weighted base with wheels; shows normal outdoor wear.",
    reference: "https://www.amazon.com/s?k=Spalding+portable+basketball+hoop+acrylic",
  },
  {
    id: 7,
    title: "Yoleo Adjustable Weight Bench with Dumbbells Set",
    category: "Other",
    price: "$80–110",
    originalPrice: "$150–200",
    condition: "Used – Good",
    status: "Available",
    image: "assets/images/1mswOvyw8sb1FrARww08k0iATYk8OgVLg.jpg",
    description: "Yoleo brand foldable/adjustable workout bench paired with adjustable dumbbell set and ab wheel, suitable for home gym use.",
    reference: "https://www.amazon.com/s?k=Yoleo+adjustable+weight+bench",
  },
];
